modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="bloodysanguimancy"
version="0.1"
displayName="Bloody Sanguimancy"
authors="Komti23"

[[dependencies.bloodysanguimancy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.bloodysanguimancy]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bloodysanguimancy]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bloodysanguimancy]]
    modId="ldlib_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bloodysanguimancy]]
    modId="photon_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
